export const categories = [
  {
    id: 1,
    name: 'Pizza',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 2,
    name: 'Noodles',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 3,
    name: 'Burger',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 4,
    name: 'Italian',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 5,
    name: 'Indian',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 6,
    name: 'Chinese',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 7,
    name: 'Desserts',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 8,
    name: 'Drinks',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 9,
    name: 'South Indian',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 10,
    name: 'Japanese',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 11,
    name: 'BBQ',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 12,
    name: 'Vegan',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 13,
    name: 'Salads',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 14,
    name: 'Biryani',
    image: require('../assets/categories/icons8-pizza-96.png'),
  },
];

export const featured = {
  id: 1,
  title: 'Hot and Spicy',
  description: 'Soft and tender fried chicken and delicious meals',
  restaurants: [
    {
      id: 1,
      name: 'Papa Johns',
      image: require('../assets/restaurants/bdcd233971b7c81bf77e1fa4471280eb (1).webp'),
      description: 'Hot and Spicy pizzas',
    latitude: 37.78825,
      longitude: -122.4324,
      address: '434 Second Street',
      stars: 4.5,
      reviews: '4.4k',
      categories: 'Fast Food',
      dishes: [
        {
          id: 1,
          name: 'Cheezy Garlic Pizza',
          description: 'Loaded with cheese and garlic butter',
          price: 10,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 2,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 3,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 4,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 5,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 6,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
      ],
    },
    {
      id: 2,
      name: 'Noodle House',
      image: require('../assets/dishes/images (2).jpeg'),

      description: 'Sizzling Asian noodles and sides',
    latitude: 37.78825,
      longitude: -122.4324,
      address: '222 Main Street',
      stars: 4.3,
      reviews: '2.1k',
      categories: 'Asian',
      dishes: [
        {
          id: 3,
          name: 'Spicy Chicken Noodles',
          description: 'Wok tossed noodles with fiery chicken',
          price: 8,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 4,
          name: 'Veg Hakka Noodles',
          description: 'Classic Indo-Chinese style noodles',
          price: 7,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 1,
          name: 'Cheezy Garlic Pizza',
          description: 'Loaded with cheese and garlic butter',
          price: 10,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 2,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 3,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 4,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 5,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 6,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
      ],
    },
    {
      id: 3,
      name: 'Tandoori Flames',
      image: require('../assets/dishes/images (2).jpeg'),
      description: 'Hot North Indian tandoori dishes',
    latitude: 37.78825,
      longitude: -122.4324,
      address: '889 Spice Avenue',
      stars: 4.7,
      reviews: '3.8k',
      categories: 'Indian',
      dishes: [
        {
          id: 5,
          name: 'Chicken Tikka',
          description: 'Grilled spicy chicken with mint chutney',
          price: 11,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 6,
          name: 'Paneer Tikka',
          description: 'Marinated paneer cubes grilled to perfection',
          price: 9,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 7,
          name: 'Tandoori Roti',
          description: 'Traditional Indian bread cooked in clay oven',
          price: 2,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 3,
          name: 'Spicy Chicken Noodles',
          description: 'Wok tossed noodles with fiery chicken',
          price: 8,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 4,
          name: 'Veg Hakka Noodles',
          description: 'Classic Indo-Chinese style noodles',
          price: 7,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 1,
          name: 'Cheezy Garlic Pizza',
          description: 'Loaded with cheese and garlic butter',
          price: 10,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 2,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 3,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 4,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 5,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
        {
          id: 6,
          name: 'Spicy Veggie Pizza',
          description: 'Hot veggies with jalapeno toppings',
          price: 12,
          image: require('../assets/dishes/images (2).jpeg'),
        },
      ],
    },
  ],
};
